name = "Academic"
license = "MIT"
licenselink = "https://github.com/wowchemy/starter-academic/blob/master/LICENSE.md"
description = "Build a professional academic or portfolio website with ease. Customize widgets, themes, and languages. One-click deployment."
homepage = "https://wowchemy.com/templates/"
min_version = "0.78"

tags = [
  "resume",
  "portfolio",
  "academic",
  "widgets",
  "responsive",
  "clean",
  "personal",
  "minimal",
  "multilingual",
  "documentation",
  "landing page",
  "projects",
  "single page",
  "contact form",
  "mobile",
  "gallery",
  "search",
  "presentation",
  "modern",
  "customizable",
  "starter",
  "technical",
  "slide",
  "courses",
  "publications",
  "talks",
  "events"
]

features = [
  "Drag-and-drop page builder",
  "Custom widgets",
  "Multiple themes and dark mode",
  "Full-text search",
  "Research publication management",
  "Filterable portfolio",
  "Online courses",
  "Events and talks",
  "Slide presentations",
  "Image and video gallery",
  "Integrated contact form",
  "Multilingual support"
]

[author]
  name = "George Cushen"
  homepage = "https://georgecushen.com"

[original]
  name = ""
  homepage = ""
  repo = ""
